name: get-data

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
    - main

jobs:
  run:
    name: Update live tracking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      - name: Fetch tracking
        run: poetry run python process.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v11
        with:
          default_author: github_actor
          message: 'Update live tracking'
          add: 'data'
